name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
#  lint:
#    name: Perform lint check
#    needs: [start]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Cache Gradle
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#          restore-keys: ${{ runner.os }}-gradle-
#
#      - name: Make Gradle executable
#        run: chmod +x ./gradlew
#
#      - name: Run lint
#        run: ./gradlew lintDebug
#
#      - name: Upload html test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html

  unit-test:
    name: Perform Unit Testing
#    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/

  debug-apk:
    name: upload to firebase
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sample-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          npm install -g firebase-tools
          
          firebase appdistribution:distribute \
            app/build/outputs/apk/debug/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --release-notes "Automated build from PR #${{ github.event.number }}" \
